// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowDown: typeof import('./src/components/arrow-down.vue')['default']
    LightBulb: typeof import('./src/components/light-bulb.vue')['default']
    SectionDaylightWhite: typeof import('./src/components/section/daylight-white.vue')['default']
    SectionHero: typeof import('./src/components/section/hero.vue')['default']
    SectionOrange: typeof import('./src/components/section/orange.vue')['default']
    SectionTexts: typeof import('./src/components/section/texts.vue')['default']
    SectionWarmWhite: typeof import('./src/components/section/warm-white.vue')['default']
    Sunshine: typeof import('./src/components/sunshine.vue')['default']
    SunshineEllipse: typeof import('./src/components/sunshine-ellipse.vue')['default']
  }
}

export {}
